[target.'cfg(any(windows, unix))']
rustflags = ["-C", "target-cpu=native", "-C", "opt-level=3", "-C", "debuginfo=2", "-C", "remark=loop-vectorize", "-C", "passes=loop-vectorize"]

#"llvm-args=-force-vector-width=16"
#"llvm-args=-ffast-math"
